site_name: iBME

repo_url: https://github.com/felixchen0707/sjtu-iBME
repo_name: felixchen0707/sjtu-iBME
edit_uri: ""

theme:
  name: material
  custom_dir: overrides


  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  icon:
    logo: logo
    repo: fontawesome/brands/github-alt
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    # - navigation.expand  # 默认情况下不要展开，防止文章数量过多
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top  # 返回顶部
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow

# MarkDown扩展
markdown_extensions:
  # 缩写支持
  - abbr

  # 列表支持
  - def_list

  # 脚注支持
  - footnotes

  - md_in_html

  - toc:
      permalink: ⚓︎

  # 表格支持
  - tables

  # 数学公式
  - pymdownx.arithmatex:
      generic: true

  # 加粗、斜体等支持
  - pymdownx.betterem

  # 高亮、下划线、删除线
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  # 代码块支持
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences

  # 行内代码
  - pymdownx.inlinehilite

  # 任务单支持
  - pymdownx.tasklist:
      custom_checkbox: true
  
  # 键盘支持
  - pymdownx.keys

extra_javascript:
  - assets/javascripts/mathjax.js
  - assets/javascripts/tex-mml-chtml.js

plugins:
  - glightbox
  - search:
  # - git-revision-date-localized:
  #     enable_creation_date: true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/felixchen0707/sjtu-iBME

copyright: Copyright &copy; Since 2022 iBME contributors

# 全站导航栏
nav:
  - 开始:
    - index.md
    
  - 课程:
    - courses/grade1/1.md

  - 关于:
    - about/contribute.md
    - about/discussion.md
    - about/contact.md